### ISSUE TITLE
[Bug/Incompatibility] Mod incompatibility causes client camera to rapidly bob up and down

### ISSUE THREAD

**Issue by JohnMetroid** [Entity378/LethalCompany_MotionTracker_V2#1]
Host does not appear to have any similar issues, but all clients joining the game exhibit this behavior despite having identical mods/configs

Issue initially reported here: https://github.com/KlutzyBubbles/lc-better-emotes/issues/24

**Comment by Entity378** [comment]
It's really strange since I tested the mod with some of my friends until recently and it never caused any problems. I also tested it in a fairly large modpack (around 90 mods) and it never gave any problems. could you send me the list of mods you used?

**Comment by Entity378** [comment]
Also @ajsglist , I would like to point out that my version of the motion tracker is temporary, I would like to make a request to the original creator of the mod but I would need people to test whether the configs are actually synchronized between client and server. if you could tell me if it actually works you would be doing me a favor.

**Comment by Entity378** [comment]
I've done some testing and can't replicate the bug.
So I don't think I can fix it.

**Comment by KlutzyBubbles** [comment]
> I've done some testing and can't replicate the bug. So I don't think I can fix it.

For both your reference and for ajsglist if they come back to reply. I did some more testing and 1.0.2 was broken, but 1.1.1 is working. 

Edit: Wrote this before checking the other notifications of you saying you fixed it lmao...

**Comment by JohnMetroid** [comment]
sorry for the late reply, just popping back in to confirm the 1.1.1 version of the tracker is working, thanks!
